CREATE TABLE IF NOT EXISTS Opinions(
ID integer NOT NULL PRIMARY KEY,
Opinion varchar(255) NOT NULL,
UserID INTEGER, 
CoffeID INTEGER,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (UserID) REFERENCES Users(ID),
FOREIGN KEY (CoffeID) REFERENCES Coffees(ID)
);